# Generated by Django 3.2.5 on 2021-07-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('has_rain', models.BooleanField(default=False)),
                ('has_temp', models.BooleanField(default=False)),
                ('has_humidity', models.BooleanField(default=False)),
                ('has_wind_speed', models.BooleanField(default=False)),
                ('has_wind_dir', models.BooleanField(default=False)),
                ('has_lux', models.BooleanField(default=False)),
                ('has_pressure', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rain', models.DecimalField(decimal_places=3, max_digits=5)),
                ('temp', models.DecimalField(decimal_places=3, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('wind_dir', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lux', models.DecimalField(decimal_places=3, max_digits=6)),
                ('pressure', models.DecimalField(decimal_places=3, max_digits=7)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_display.station')),
            ],
        ),
    ]
